### ISSUE TITLE
Estimated value of R in the compartmental model

### ISSUE THREAD

**Issue by bgyori** [tamas-ferenci/COVID19MagyarEpi#2]
The forecasts use a value of 2.69 for R by default, but the two methods for estimating R with a sliding window are in the ~1.4 range. Would it make sense to use these estimates of R as the default when displaying the forecast? Or am I missing something?

**Comment by ferenci-tamas** [comment]
Thanks @bgyori for your comment! You're totally right, the present value used in the long-term forecast (compartmental model) is a way larger than the actual value. But you can easily overcome this: if you set the mode to Szcenárióelemzés, you can arbitrarily change the value of R, which means you can set it to arbitrary value, and you're also completely free to choose the date of change. Thus, you can even set it to to very first day, set the deviation to -1.3, and there you have the ~1.4 scenario!
