### ISSUE TITLE
Semi-automatic data update based on pandemic.hu

### ISSUE THREAD

**Issue by herczegrobert** [tamas-ferenci/COVID19MagyarEpi#4]
Dear Tamás,

I've found this website pandemic.hu which uses a visualisation webservice. They have a public service, therefore, you can access the data. It has to be manually copied but is is a little bit better than koronvirus.gov.hu.

https://public.flourish.studio/visualisation/1644908

You can find the author here: https://app.flourish.studio/@esotanc
I think, he also collects the data by hand. Maybe it worth to ask him.

There is an API service at flourish.

Best,
Robert

**Comment by ferenci-tamas** [comment]
Thanks @herczegrobert very much for the suggestion! Unfortunately I'm afraid that you're right and what they do is simply typing in manually the numbers from the official site, i.e., the exact same thing that I do, so I rather don't use them, simply to avoid having a further dependency in the downstream. Besides, I really-really do hope that this whole issue is temporary, and NNK will start publishing data in some meaningful format... (I might be too naive).
